// Use this file to write queries to test your data connector
let
//    result = FacebookAds.GetCampaignInsights2("6082518097232")
    result = FacebookAds.Ads()
//    result = FacebookAds.GetAllAdInsights([id = "act_311750606"]),
//    result = FacebookAds.AdAccountsToNavigationTable({[id = "act_311750606", name = "My"]})
//    result = FacebookAds.GetAllAdInsights([id = "act_311750606", name = "My"])
in
    result